### ISSUE TITLE
Triage query incorrectly showing issues that have milestones

### ISSUE THREAD

**Issue by tommcdon** [terrajobst/issuesof.net#28]
Issues of .NET is showing 3 github issues in the query below that are marked as triaged and have a milestone but still nonetheless show up in the query:

https://issuesof.net/?q=is%3Aopen%20is%3Aissue%20repo%3Aruntime%20%20NOT%20%28label%3Aos-android%20or%20label%3Aos-maccatalyst%20or%20label%3Aos-ios%20or%20label%3Aos-tvos%20or%20label%3Aarch-wasm%29%20%28label%3Aarea-system.diagnostics%20or%20label%3Aarea-system.diagnostics.activity%20or%20label%3Aarea-tracing-coreclr%20or%20label%3Aarea-system.diagnostics.metric%20or%20label%3Aarea-diagnostics-coreclr%20or%20label%3Aarea-system.diagnostics.tracing%20or%20label%3Aarea-uwp%29%20no%3Amilestone

Org|Repo|Type|State|Number|Title|Comments|ReactionsPlus1|ReactionsMinus1|ReactionsSmile|ReactionsTada|ReactionsThinkingFace|ReactionsHeart|Reactions|Interactions
---|---|---|---|---|---|---|---|---|---|---|---|---|---|---
dotnet|runtime|Issue|open|78940|"Debugging execution code in vs is slow| but the program is compiled and runs fine"|2|0|0|0|0|0|0|0|2
dotnet|runtime|Issue|open|78956|The createdump tool creates double crash dumps when running in a Linux container on Kubernetes|1|0|0|0|0|0|0|0|1
dotnet|runtime|Issue|open|78538|Incomplete managed stacktrace in windbg|1|0|0|0|0|0|0|0|1

**Comment by terrajobst** [comment]
This is now fixed as the index is up-to-date again.
