### ISSUE TITLE
Shows outdated labels and incorrect milestones on issues

### ISSUE THREAD

**Issue by lambdageek** [terrajobst/issuesof.net#29]
This query https://issuesof.net/?q=is%3Aopen%20is%3Aissue%20%28area-node%3Amono%20or%20label%3Aos-maccatalyst%20or%20label%3Aos-android%20or%20label%3Aos-ios%20or%20label%3Aarch-wasm%29%20%28no%3Amilestone%20or%20label%3Auntriaged%29%20add%20test currently displays one issue:

https://github.com/dotnet/runtime/issues/79010

The display on issuesof.net shows the labels: `test-enhancement` `untriaged` and `area-Build-mono` and no milestone set.  But when I visit the issue, instead it has the labels`area-Build-mono`and `test-enhancement` without `untriaged` and a milestone of `8.0.0`

**Comment by terrajobst** [comment]
This should be fixed now, as the index is current again.
