### ISSUE TITLE
Stats table overflow on iOS

### ISSUE THREAD

**Issue by fowl2** [terrajobst/issuesof.net#32]
See example screenshot (using Twitter iOS in app browser) here: ![image](https://github.com/terrajobst/issuesof.net/assets/12844147/f0e7c09d-d510-41e2-9cde-e4111faf088c)

iOS 17.2 (21C5054b)

iPhone 15 Plus

Edit: to clarify, I zoomed out - it loads like this, where there's no visual indication there are other columns: 

![image](https://github.com/terrajobst/issuesof.net/assets/12844147/74162678-498a-40c6-a891-25a09203aab7)

**Comment by terrajobst** [comment]
To be honest, I'm not sure I care enough to fix mobile :-(
