### ISSUE TITLE
Include "microsoft" organization

### ISSUE THREAD

**Issue by AmrAlSayed0** [terrajobst/issuesof.net#4]
App Center SDK https://github.com/microsoft/appcenter-sdk-dotnet
App Center Unity SDK https://github.com/microsoft/appcenter-sdk-unity
OData to OpenAPI.NET https://github.com/microsoft/OpenAPI.NET.OData
Mixed Reality Toolkit https://github.com/microsoft/MixedRealityToolkit-Unity
Bot Framework SDK for .NET https://github.com/microsoft/botbuilder-dotnet
FHIR Server for Azure https://github.com/microsoft/fhir-server
Project Reunion https://github.com/microsoft/ProjectReunion
InferSharp https://github.com/microsoft/infersharp
Windows UI Library https://github.com/microsoft/microsoft-ui-xaml
Application Insights for .NET https://github.com/microsoft/ApplicationInsights-dotnet
FASTER https://github.com/microsoft/FASTER
C#/WinRT Language Projection https://github.com/microsoft/CsWinRT
Armada https://github.com/microsoft/Armada
Visual Studio MI Debug Engine ("MIEngine") https://github.com/microsoft/MIEngine
Coyote https://github.com/microsoft/coyote
Microsoft.Unity.Analyzers https://github.com/microsoft/Microsoft.Unity.Analyzers
Bot Framework Components https://github.com/microsoft/botframework-components
LLVMSharp https://github.com/microsoft/LLVMSharp
And there are probably much more repos that are relevant to .NET

**Comment by terrajobst** [comment]
The goal of issuesof.net isn't necessarily to index all repos that do anything with .NET; the goal is to represent the issues of the .NET platform, and in cases where appropriate, including .NET Foundation projects.

The reason for that is scale. I'm operating the web site in a standard Azure app service and indexing the world would make it harder to provide good performance for the site.

**Comment by terrajobst** [comment]
Fixed in ea7a8893d75b48ea6bfea7438a82cbbd0ef14594

**Comment by AmrAlSayed0** [comment]
Ultimately you decide what gets included but I think at least the 2 WinUI repos is worth including:
- Project Reunion https://github.com/microsoft/ProjectReunion
Windows UI Library https://github.com/microsoft/microsoft-ui-xaml
