### ISSUE TITLE
on iPhone / Safari after expanding, the page refreshed and lose your spot

### ISSUE THREAD

**Issue by burtonrodman** [terrajobst/issuesof.net#5]
visit site on iPhone (Safari)
expand the default results
after a few seconds the content collapses and loses your spot

**Comment by terrajobst** [comment]
I assume you're grouping?

**Comment by burtonrodman** [comment]
-on my iPhone, in the Outlook app, I followed the link to issuesof.net [here](https://github.com/aspnet/Announcements/pull/469#issuecomment-886866309)
-at that time 1 group was displayed (i now see 2 groups)
-after expanding the group and scrolling down through the issues, the page refreshed or the group collapsed (not sure which)

**Comment by terrajobst** [comment]
Yeah, that's an issue because I don't have a good way to store expansion / collapsing state when re-running queries. I've disabled automatic page refresh when an issue changes, which at least addresses this issue.
