### ISSUE TITLE
Index seems to keep returning issues that have been moved out when using the "repo" query

### ISSUE THREAD

**Issue by hoyosjs** [terrajobst/issuesof.net#6]
Consider this query: `is:open is:issue repo:runtime  NOT (label:os-android or label:os-maccatalyst or label:os-ios or label:os-tvos or label:arch-wasm) (label:area-diagnostics-coreclr) milestone:6.0.0` [quick link](https://issuesof.net/?q=is%3Aopen%20is%3Aissue%20repo%3Aruntime%20%20NOT%20%28label%3Aos-android%20or%20label%3Aos-maccatalyst%20or%20label%3Aos-ios%20or%20label%3Aos-tvos%20or%20label%3Aarch-wasm%29%20%28label%3Aarea-diagnostics-coreclr%29%20milestone%3A6.0.0)

Issue dotnet/runtime#56037 appears there, though it's been moved to https://github.com/dotnet/sdk/issues/19674. This issue now doesn't have that area tag and is not part of the milestone anymore.

**Comment by terrajobst** [comment]
Thanks. There is an indexing issue; I’m not entirely where the stale data is coming from.

**Comment by terrajobst** [comment]
This should be fixed now as the index is up-to-date again.
